services:
  loyalty_api:
    container_name: loyalty_api_service
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6910:6910"
      - "6911:6911"
    networks:
      - loyalty_network
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 6910 --reload
    depends_on:
      loyalty_postgres_db:
        condition: service_healthy   # ← API стартует ТОЛЬКО после готовности БД

  loyalty_postgres_db:
    container_name: loyalty_postgres_db
    image: postgres:15
    restart: always
    shm_size: 128mb
    ports:
      - "6955:5432"
    volumes:
      - loyalty_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: loyalty_db
    networks:
      - loyalty_network
    healthcheck:                      # ← Проверка готовности БД
      test: ["CMD-SHELL", "pg_isready -U root -d loyalty_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  loyalty_postgres_data:

networks:
  loyalty_network:
    driver: bridge